// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf57k4aeW26t7Ojw43IiwMyzAaCOm2HNc',
    appId: '1:152134110112:web:4344ad929dfcba1042b2c5',
    messagingSenderId: '152134110112',
    projectId: 'uplift-2316e',
    authDomain: 'uplift-2316e.firebaseapp.com',
    databaseURL: 'https://uplift-2316e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uplift-2316e.appspot.com',
    measurementId: 'G-TLMQEGB7EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH6E2nSn4TBNiKedH_P5qQm83fUrQxgx8',
    appId: '1:152134110112:android:709c7b6e87d5fd6942b2c5',
    messagingSenderId: '152134110112',
    projectId: 'uplift-2316e',
    databaseURL: 'https://uplift-2316e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uplift-2316e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXDbiT8KXRGjA3sHgjnF42Fh6ljOOlxTY',
    appId: '1:152134110112:ios:00b23915778a03b242b2c5',
    messagingSenderId: '152134110112',
    projectId: 'uplift-2316e',
    databaseURL: 'https://uplift-2316e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uplift-2316e.appspot.com',
    androidClientId: '152134110112-6aeu9js7i7u6gddh05mg9ftkrhqiirup.apps.googleusercontent.com',
    iosClientId: '152134110112-10bd6drt8af151irmhmv8cl3r664dp44.apps.googleusercontent.com',
    iosBundleId: 'com.godesq.uplift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXDbiT8KXRGjA3sHgjnF42Fh6ljOOlxTY',
    appId: '1:152134110112:ios:00b23915778a03b242b2c5',
    messagingSenderId: '152134110112',
    projectId: 'uplift-2316e',
    databaseURL: 'https://uplift-2316e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uplift-2316e.appspot.com',
    androidClientId: '152134110112-6aeu9js7i7u6gddh05mg9ftkrhqiirup.apps.googleusercontent.com',
    iosClientId: '152134110112-10bd6drt8af151irmhmv8cl3r664dp44.apps.googleusercontent.com',
    iosBundleId: 'com.godesq.uplift',
  );
}
